# -*- coding: utf-8 -*-
"""Project 124

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gM2PBCewtMFBFPWbjkt5kht09P6qDXTM
"""

from flask import Flask, jsonify, request
app = Flask(__name__)
List = [{
    'id': 1,
    'name': u'Ishan',
    'Contact': u'(123)-456-7890',
    'done': False
},
{
    'id': 2,
    'name': u'John',
    'Contact': u'(098)-765-4321',
    'done': False
}]
@app.route("/")
def helloworld():
  return "Hello World"
@app.route("/add-data", methods = ["POST"])
def addtask():
  if not request.json:
    return jsonify({
        "Status": "Error",
        "Message": "Please provide data"
    }, 400)
  contact = {
      'id': List[-1]['id'] + 1,
    'name': request.json['name'],
    'Contact': request.json.get('Contact', ""),
    'done': False
  }
  List.append(contact)
  return jsonify({
        "Status": "Success",
        "Message": "Contact added successfully"  
  }, 200)
@app.route("/get-data")
def gettask():
  return jsonify({"data": List})
if (__name__ == "__main__"):
  app.run(debug = True)